### ISSUE TITLE
Problème lors de la modification des paramètres.

### ISSUE THREAD

**Issue by TapsHTS** [L-C-B/SpectreLauncher#1]
@L-C-B ou @LaCarotteBleue Quand je modifie la version ainsi que la ram et que j'appuie sur "Save" on ne retourne pas sur la page d'accueil ? Comment régler cela ?

**Comment by L-C-B** [comment]
C'est normal, je n'arrive encore pas à save la version & la ram mais j'y travaille. J'essayerai de vous tenir au courant quand ce sera possible.
Bonne journée.

**Comment by L-C-B** [comment]
Bonsoir @TapsHTS, le problème a été réglé, vous pouvez dorénavant modifier la mémoire vive et la version sans problèmes.
Bonne soirée.
